<?xml version="1.0" ?>
<robot name='robot' xmlns:xacro="http://ros.org/wiki/xacro">

    <xacro:include filename="$(find robot_description)/urdf/gazebo.urdf.xacro" />
    <!--xacro:include filename="$(find robot_description)/urdf/lidar.urdf.xacro" /-->
    <!--xacro:include filename="$(find robot_description)/urdf/depth.urdf.xacro" /-->

    <xacro:property name="chassis_radius" value="0.15"/>
    <xacro:property name="chassis_height" value="0.138"/>
    <xacro:property name="wheel_radius" value="0.033"/>
    <xacro:property name="wheel_thickness" value="0.026"/>
    <xacro:property name="wheel_mass" value="0.05"/>
    <xacro:property name="wheel_offset_x" value="0.176"/>
    <xacro:property name="wheel_offset_y" value="0.1485"/>
    <xacro:property name="wheel_offset_z" value="0.01"/>
    <xacro:property name="caster_wheel_radius" value="0.01"/>
    <xacro:property name="caster_wheel_mass" value="0.01"/>
    <xacro:property name="caster_wheel_offset_x" value="0.315"/>
    <xacro:property name="caster_wheel_offset_z" value="${wheel_offset_z - wheel_radius + caster_wheel_radius}"/>
    <xacro:property name="mass" value="1.0"/>

    <xacro:property name="eye_radius" value="0.03"/>
    <xacro:property name="eye_offset_x" value="0.350"/>
    <xacro:property name="eye_offset_y" value="0.0"/>
    <xacro:property name="eye_offset_z" value="${chassis_height/2 + eye_radius}"/>

    <xacro:property name="eye_radius2" value="0.015"/>
    <xacro:property name="eye_offset_x2" value="0.368"/>
    <xacro:property name="eye_offset_y2" value="0.0"/>
    <xacro:property name="eye_offset_z2" value="${chassis_height/2 * 1.15 + eye_radius2}"/>
    
    <material name="white">
        <color rgba="1 1 1 1" />
    </material>

    <material name="purple">
        <color rgba="0.4 0.3 0.9 1"/>
    </material>

    <material name="orange">
        <color rgba="1 0.3 0.1 1"/>
    </material>

    <material name="blue">
        <color rgba="0.2 0.2 1 1"/>
    </material>

    <material name="black">
        <color rgba="0 0 0 1"/>
    </material>

    <material name="red">
        <color rgba="1 0 0 1"/>
    </material>

    <link name="base_link">
    </link>

    <link name="base_footprint">
    </link>

    <joint name="base_footprint_joint" type="fixed">
        <parent link="base_link"/>
        <child link="base_footprint"/>
        <origin xyz="0 0 -0.138" rpy="0 0 0"/>
    </joint>

    <joint name="chassis_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chassis"/>
        <origin xyz="${-wheel_offset_x} 0 ${-wheel_offset_z}"/>
    </joint>

    <link name='chassis'>
        <inertial>
            <origin xyz="${chassis_height*1.5} 0 ${chassis_height/2}" rpy="0 0 0"/>
            <mass value="${mass}" />
            <inertia ixx="${(1/12) * mass * (3*chassis_radius*chassis_radius + chassis_height*chassis_height)}" ixy="0.0" ixz="0.0"
                     iyy="${(1/12) * mass * (3*chassis_radius*chassis_radius + chassis_height*chassis_height)}" iyz="0.0"
                     izz="${(1/2) * mass * (chassis_radius*chassis_radius)}" />
        </inertial>
        <visual>
            <origin xyz="${chassis_height*1.5} 0 ${chassis_height/2}"/>
            <geometry>
                <cylinder radius="${chassis_radius}" length="${chassis_height}"/>
            </geometry>
            <material name="purple"/>
        </visual>
        <collision>
            <origin xyz="${chassis_height*1.5} 0 ${chassis_height/2}"/>
            <geometry>
                 <cylinder radius="${chassis_radius}" length="${chassis_height}"/>
            </geometry>
        </collision>
    </link>

    <!-- <gazebo reference="chassis">
        <material>Gazebo/Purple</material>
    </gazebo> -->

    <joint name="left_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="left_wheel"/>
        <origin xyz="0 ${wheel_offset_y} 0" rpy="-${pi/2} 0 0" />
        <axis xyz="0 0 1"/>
    </joint>

    <link name="left_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="${wheel_mass}" />
            <inertia ixx="${(1/12) * wheel_mass * (3*wheel_radius*wheel_radius + wheel_thickness*wheel_thickness)}" ixy="0.0" ixz="0.0"
                     iyy="${(1/12) * wheel_mass * (3*wheel_radius*wheel_radius + wheel_thickness*wheel_thickness)}" iyz="0.0"
                     izz="${(1/2) * wheel_mass * (wheel_radius*wheel_radius)}" />
        </inertial>
    </link>

    <gazebo reference="left_wheel">
        <material>Gazebo/White</material>
    </gazebo>

    <joint name="right_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="right_wheel"/>
        <origin xyz="0 ${-wheel_offset_y} 0" rpy="${pi/2} 0 0" />
        <axis xyz="0 0 -1"/>
    </joint>

    <link name="right_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="${wheel_mass}" />
            <inertia ixx="${(1/12) * wheel_mass * (3*wheel_radius*wheel_radius + wheel_thickness*wheel_thickness)}" ixy="0.0" ixz="0.0"
                     iyy="${(1/12) * wheel_mass * (3*wheel_radius*wheel_radius + wheel_thickness*wheel_thickness)}" iyz="0.0"
                     izz="${(1/2) * wheel_mass * (wheel_radius*wheel_radius)}" />
        </inertial>
    </link>

    <gazebo reference="right_wheel">
        <material>Gazebo/White</material>
    </gazebo>

    <joint name="caster_wheel_joint" type="fixed">
        <parent link="chassis"/>
        <child link="caster_wheel"/>
        <origin xyz="${caster_wheel_offset_x} 0 ${caster_wheel_offset_z}"/>
    </joint>


    <link name="caster_wheel">
        <visual>
            <geometry>
                <sphere radius="${caster_wheel_radius}"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${caster_wheel_radius}"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="${caster_wheel_mass}" />
            <inertia ixx="${(2/5) * caster_wheel_mass * (caster_wheel_radius*caster_wheel_radius)}" ixy="0.0" ixz="0.0"
                     iyy="${(2/5) * caster_wheel_mass * (caster_wheel_radius*caster_wheel_radius)}" iyz="0.0"
                     izz="${(2/5) * caster_wheel_mass * (caster_wheel_radius*caster_wheel_radius)}" />
        </inertial>
    </link>

    <gazebo reference="caster_wheel">
        <material>Gazebo/White</material>
        <mu1 value="0.001"/>
        <mu2 value="0.001"/>
    </gazebo>

    <joint name="eye_joint" type="fixed">
        <parent link="chassis"/>
        <child link="eye"/>
        <origin xyz="${eye_offset_x} ${eye_offset_y} ${eye_offset_z}"/>
    </joint>

    <link name="eye">
        <visual>
            <geometry>
                <sphere radius="${eye_radius}"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${eye_radius}"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="0.01" />
            <inertia ixx="${(2/5) * 0.01 * (eye_radius*eye_radius)}" ixy="0.0" ixz="0.0"
                     iyy="${(2/5) * 0.01 * (eye_radius*eye_radius)}" iyz="0.0"
                     izz="${(2/5) * 0.01 * (eye_radius*eye_radius)}" />
        </inertial>
    </link>

    <gazebo reference="eye">
        <material>Gazebo/White</material>
    </gazebo>


    <joint name="eye_joint2" type="fixed">
        <parent link="chassis"/>
        <child link="eye2"/>
        <origin xyz="${eye_offset_x2} ${eye_offset_y2} ${eye_offset_z2}"/>
    </joint>

    <link name="eye2">
        <visual>
            <geometry>
                <sphere radius="${eye_radius2}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${eye_radius2}"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="0.01" />
            <inertia ixx="${(2/5) * 0.01 * (eye_radius2*eye_radius2)}" ixy="0.0" ixz="0.0"
                     iyy="${(2/5) * 0.01 * (eye_radius2*eye_radius2)}" iyz="0.0"
                     izz="${(2/5) * 0.01 * (eye_radius2*eye_radius2)}" />
        </inertial>
    </link>

    <gazebo reference="eye2">
        <material>Gazebo/Black</material>
    </gazebo>

</robot>